# base values file

registry:
  base:  ghcr.io/learnlib/alex
certManager:
  email:
selenium:
  chrome:
    replicas: 1
    resources:
      cpu: ".5"
      memory: "1000Mi"
  firefox:
    replicas: 1
    resources:
      cpu: ".5"
      memory: "1000Mi"
