version: '3.3'
services:
    selenium-hub:
        image: selenium/hub:3
        ports:
            - 4444:4444
        networks:
            - backend
    chrome-node:
        image: selenium/node-chrome-debug:3
        shm_size: '2gb'
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
        ports:
            - 5900:5900
        networks:
            - backend
    firefox-node:
        image: selenium/node-firefox-debug:3
        shm_size: '2gb'
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
        ports:
            - 5901:5900
        networks:
            - backend
    alex-backend-development:
        image: maven:3-jdk-11
        depends_on:
            - selenium-hub
        working_dir: /var/alex/backend
        volumes:
            - ./backend/src:/var/alex/backend/src:ro
            - ./backend/pom.xml:/var/alex/backend/pom.xml:ro
            - alex-backend-maven-development:/root/.m2
            - alex-backend-db-development:/var/alex/backend/target/db
            - alex-backend-files-development:/var/alex/backend/target/files
        command: mvn spring-boot:run -Dspring-boot.run.arguments="--webdriver.remote.url=http://selenium-hub:4444/wd/hub"
        ports:
            - 8000:8000
        networks:
            - backend
            - frontend
    alex-frontend-development:
        image: node
        working_dir: /var/alex/frontend
        volumes:
            - ./frontend:/var/alex/frontend:rw
        command: npm run start:docker
        ports:
            - 4200:4200
        networks:
            - frontend

volumes:
  alex-backend-maven-development:
  alex-backend-db-development:
  alex-backend-files-development:

networks:
    frontend:
    backend: