version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    env_file:
      - ./backend.env
    command: /bin/sh -c "envsubst '$${SERVER_ADDRESS},$${PORT}' < /usr/share/nginx/html/assets/config.template.json > /usr/share/nginx/html/assets/config.json && exec nginx -g 'daemon off;'"
  backend:
    build: ./backend
    ports:
      - 8000:8000