version: '3.3'
services:
  selenium-hub:
    image: selenium/hub:3
    networks:
      - backend
  chrome-node:
    image: selenium/node-chrome-debug:3
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - backend
  firefox-node:
    image: selenium/node-firefox-debug:3
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - backend
  alex-database-production:
    image: postgres:10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=sa
      - POSTGRES_DB=alex
    volumes:
      - alex-database-production:/var/lib/postgresql
    networks:
      - backend
    ports:
      - "127.0.0.1:5432:5432"
  alex-backend-production:
    build: ./backend
    volumes:
      - alex-database-production:/var/alex/backend/target/postgresql
    environment:
      - REMOTE_DRIVER=http://selenium-hub:4444/wd/hub
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - backend
  alex-frontend-production:
    build: ./frontend
    environment:
      - SERVER_ADDRESS=http://localhost
      - PORT=8000
    ports:
      - "127.0.0.1:4200:4200"
    networks:
      - frontend

volumes:
  alex-database-production: