version: '3.3'
services:
  selenium-hub:
    image: selenium/hub:3
  chrome-node:
    image: selenium/node-chrome-debug:3
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox-node:
    image: selenium/node-firefox-debug:3
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  alex-frontend:
    image: ghcr.io/learnlib/alex/alex-frontend:unstable
    environment:
      - SERVER_ADDRESS=http://localhost
      - PORT=8000
    ports:
      - 80:4200
  alex-backend:
    image: ghcr.io/learnlib/alex/alex-backend:unstable
    volumes:
      - alex-backend-db:/var/lib/alex/target/db
      - alex-backend-files:/var/lib/alex/target/files
    environment:
      - REMOTE_DRIVER=http://selenium-hub:4444/wd/hub
    ports:
      - 8000:8000

volumes:
  alex-backend-db:
  alex-backend-files: