apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: alex
deploy:
  helm:
    releases:
      - name: release
        artifactOverrides:
          frontendImage: ghcr.io/learnlib/alex/alex-frontend
          backendImage: ghcr.io/learnlib/alex/alex-backend
        chartPath: ./infrastructure/helm-chart
        valuesFiles:
          - ./infrastructure/helm-chart/values.yaml
          - ./infrastructure/helm-chart/values-local.yaml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ghcr.io/learnlib/alex/alex-frontend
      context: ./frontend
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/learnlib/alex/alex-backend
      context: ./backend
      docker:
        dockerfile: Dockerfile

profiles:
  # profile that can be used to deploy ALEX to an arbitrary, temporary server
  # run with `skaffold run -p temp`
  - name: temp
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm-chart/values-temp.yaml