apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 4200
  selector:
    app: frontend
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  labels:
    app: frontend
data:
  ALEX_BACKEND_ADDRESS: http://{{ .Values.ingress.host }}
  ALEX_BACKEND_PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: '{{.Values.registry.base}}/alex-frontend:{{ .Chart.AppVersion }}'
          envFrom:
            - configMapRef:
                name: frontend
      restartPolicy: Always
