apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-firefox
  labels:
    app: selenium-node-firefox
spec:
  replicas: {{ .Values.selenium.firefox.replicas }}
  selector:
    matchLabels:
      app: selenium-node-firefox
  template:
    metadata:
      labels:
        app: selenium-node-firefox
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-firefox
          image: selenium/node-firefox:4.8.1
          ports:
            - containerPort: 5900
            - containerPort: 7900
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: NODE_PORT
              value: "5900"
          resources:
            limits:
              memory: {{ .Values.selenium.firefox.memory }}
              cpu: {{ .Values.selenium.firefox.cpu }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-firefox-scaledobject
  labels:
    deploymentName: selenium-node-firefox
spec:
  minReplicaCount: 1
  maxReplicaCount: 80
  pollingInterval: 10
  scaleTargetRef:
    name: selenium-node-firefox
  triggers:
    - type: selenium-grid
      metadata:
        url: 'http://selenium-hub.{{ .Release.Namespace}}.svc.cluster.local:4444/graphql'
        browserName: 'firefox'
