package de.learnlib.weblearner.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.hibernate.validator.constraints.NotBlank;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.ws.rs.Produces;
import java.util.HashSet;
import java.util.Set;

@Entity
public class SymbolGroup {

    /** The ID of the SymbolGroup in the DB. */
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @JsonIgnore
    private Long groupId;

    @NotBlank
    private String name;

    @ManyToOne
    @JsonIgnore
    private Project project;

    private Long id;

    @OneToMany
    private Set<Symbol> symbols;

    public SymbolGroup() {
        this(0L);
    }

    public SymbolGroup(Long groupId) {
        this.groupId = groupId;
        this.id = 0L;
        this.symbols = new HashSet<>();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @JsonProperty("project")
    public long getProjectId() {
        if (project == null) {
            return 0L;
        }
        return project.getId();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Symbol> getSymbols() {
        return symbols;
    }

    public void setSymbols(Set<Symbol> symbols) {
        this.symbols = symbols;
    }

    @JsonProperty("symbolAmount")
    public int getSymbolSize() {
        return this.symbols.size();
    }

    public void addSymbol(Symbol symbol) {
        symbols.add(symbol);
    }

    //CHECKSTYLE.OFF: AvoidInlineConditionals|MagicNumber - auto generated by Intellij IDEA

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SymbolGroup that = (SymbolGroup) o;

        if (!id.equals(that.id)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    // CHECKSTYLE.OFF: AvoidInlineConditionals|MagicNumber
}
