package de.learnlib.alex.core.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Transient;
import java.io.Serializable;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Embeddable statistics object to hold all the statistics together.
 */
@Embeddable
@JsonPropertyOrder(alphabetic = true)
public class Statistics implements Serializable {

    private static final long serialVersionUID = -5221139436025380739L;

    /** Standard DateTimeFormatter that will create a nice ISO 8160 string with milliseconds and a time zone. */
    public static final DateTimeFormatter DATE_TIME_FORMATTER
                                                        = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSxxx");

    /** A ZonedDateTime object based at the unix time 0. */
    private static final ZonedDateTime UNIX_TIME_START = ZonedDateTime.parse("1970-01-01T00:00:00.000+00:00");

    /**
     * Sub Statistics class to store information by Learner and EqOracle.
     */
    @Embeddable
    public static class DetailedStatistics implements Serializable {

        private static final long serialVersionUID = -2601019208764457063L;

        /** Data of the Learner. */
        private long learner;

        /** Data of the EqOracle. */
        private long eqOracle;

        /**
         * Default constructor.
         */
        public DetailedStatistics() {
            this(0L, 0L);
        }

        /**
         * @param learner
         *         Data of the Learner.
         * @param eqOracle
         *         Data of the EqOracle.
         */
        public DetailedStatistics(long learner, long eqOracle) {
            this.learner = learner;
            this.eqOracle = eqOracle;
        }

        /**
         * @return The total data, i.e. Learner data + EqOracle data.
         */
        @Transient
        @JsonProperty("total")
        public long getTotal() {
            return learner + eqOracle;
        }

        /**
         * @return Current data of the Learner.
         */
        @JsonProperty("learner")
        public long getLearner() {
            return learner;
        }

        /**
         * @param learner
         *         New data of the Learner.
         */
        public void setLearner(long learner) {
            this.learner = learner;
        }

        /**
         * @return Current data of the EqOracle.
         */
        @JsonProperty("eqOracle")
        public long getEqOracle() {
            return eqOracle;
        }

        /**
         * @param eqOracle
         *         New data of the EqOracle.
         */
        public void setEqOracle(long eqOracle) {
            this.eqOracle = eqOracle;
        }

        /**
         * Increment the values of the Learner and EqOracle data by another DetailedStatistics.
         *
         * @param offset
         *         A DetailedStatistics with the values to add.
         */
        public void increment(DetailedStatistics offset) {
            this.learner  += offset.learner;
            this.eqOracle += offset.eqOracle;
        }

        @Override
        @SuppressWarnings({"checkstyle:needbraces", "checkstyle:operatorwrap"}) // Auto generated by IntelliJ
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            DetailedStatistics that = (DetailedStatistics) o;
            return learner == that.learner &&
                    eqOracle == that.eqOracle;
        }

        @Override
        public int hashCode() {
            return Objects.hash(learner, eqOracle);
        }
    }

    /**
     * Date and Time when the learning step was started.
     * The format is conform with the ISO 8601 (JavaScript-Style).
     */
    @JsonIgnore
    private ZonedDateTime startDate;

    /**
     * The 'time' the test started in nanoseconds.
     * This is just internally user to calculate the duration and the Java value for the used 'nanoTime' has no
     * real world meaning.
     */
    @JsonIgnore
    private long startTime;

    /** The amount of equivalence queries. */
    private long eqsUsed;

    /** The duration of the learn step. */
    private DetailedStatistics duration;

    /** The amount of membership queries/ SUL resets. */
    private DetailedStatistics mqsUsed;

    /** The amount of actual symbols called during the learning process. */
    private DetailedStatistics symbolsUsed;

    /**
     * Default constructor.
     */
    public Statistics() {
        this.startDate   = UNIX_TIME_START;
        this.startTime   = 0L;
        this.eqsUsed     = 0L;
        this.duration    = new DetailedStatistics();
        this.mqsUsed     = new DetailedStatistics();
        this.symbolsUsed = new DetailedStatistics();
    }

    /**
     * Get the start time of the learn step.
     *
     * @return The start time.
     */
    public long getStartTime() {
        return startTime;
    }

    /**
     * Set the start time.
     *
     * @param startTime
     *          The time in ns
     */
    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    /**
     * Get the date of when the test run started.
     *
     * @return The date
     */
    @JsonIgnore
    public ZonedDateTime getStartDate() {
        return startDate;
    }

    /**
     * Set the date when the test started.
     *
     * @param startDate
     *          The date object
     */
    @JsonIgnore
    public void setStartDate(ZonedDateTime startDate) {
        this.startDate = startDate;
    }

    /**
     * @return When the learning was started as nice ISO 8160 string, including milliseconds and zone.
     */
    @Transient
    @JsonProperty("startDate")
    public String getStartDateAsString() {
        return startDate.format(DATE_TIME_FORMATTER);
    }

    /**
     * @param dateAsString The point in time when the learning was started.
     */
    @JsonProperty("startDate")
    public void setStartDateByString(String dateAsString) {
        this.startDate = ZonedDateTime.parse(dateAsString);
    }

    /**
     * Get the amount of equivalence oracles used during the learning.
     *
     * @return The amount of eq oracles.
     */
    public long getEqsUsed() {
        return eqsUsed;
    }

    /**
     * Set the amount of equivalence oracles used during the learning.
     *
     * @param eqsUsed
     *         The new amount of eq oracles.
     */
    public void setEqsUsed(long eqsUsed) {
        this.eqsUsed = eqsUsed;
    }

    /**
     * @return The duration.
     */
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "learner",  column = @Column(name = "duration_learner")),
        @AttributeOverride(name = "eqOracle", column = @Column(name = "duration_eqOracle"))
    })
    public DetailedStatistics getDuration() {
        return duration;
    }

    /**
     * @param duration
     *         The new duration
     */
    public void setDuration(DetailedStatistics duration) {
        this.duration = duration;
    }

    /**
     * @return The amount of MQs.
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "learner",  column = @Column(name = "mqs_learner")),
            @AttributeOverride(name = "eqOracle", column = @Column(name = "mqs_eqOracle"))
    })
    public DetailedStatistics getMqsUsed() {
        return mqsUsed;
    }

    /**
     * @param mqsUsed
     *         The new amount of MQs.
     */
    public void setMqsUsed(DetailedStatistics mqsUsed) {
        this.mqsUsed = mqsUsed;
    }

    /**
     * @return The amount of symbols used.
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "learner",  column = @Column(name = "symbolUsed_learner")),
            @AttributeOverride(name = "eqOracle", column = @Column(name = "symbolUsed_eqOracle"))
    })
    public DetailedStatistics getSymbolsUsed() {
        return symbolsUsed;
    }

    /**
     * @param symbolsUsed
     *         The new amount of symbols used during the learning.
     */
    public void setSymbolsUsed(DetailedStatistics symbolsUsed) {
        this.symbolsUsed = symbolsUsed;
    }
}
