name: release-docker-image
description: release a docker image to the github registry

inputs:
  username:
    description: 'GitHub username'
    required: true
  password:
    description: 'GitHub password'
    required: true
  image:
    description: 'Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      shell: bash
      run: echo "${{ inputs.password }}" | docker login https://ghcr.io -u ${{ inputs.username }} --password-stdin

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.image }}-image

    - name: Push to GitHub Container Registry
      shell: bash
      run: |
        IMAGE_ID=ghcr.io/learnlib/alex/${{ inputs.image }}
        BRANCH=${GITHUB_REF#"refs/heads/"}
        VERSION=

        if [ "$BRANCH" == "developer" ]
        then
          VERSION="unstable"
        elif [ "$BRANCH" == "master" ]
        then
          VERSION="latest"
        else
          VERSION="$GITHUB_SHA"
        fi

        docker load < ${{ inputs.tag }}-image.tar.gz
        docker tag ${{ inputs.tag }} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
