spring:
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  devtools:
    remote:
      secret: "mysecret"
  datasource:
    initialization-mode: "always"
    platform: "postgres"
    url: "jdbc:postgresql://alex-database:5432/alex"
    username: "sa"
    hikari:
      connection-test-query: "SELECT 1"
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
  servlet:
    multipart:
      max-file-size: "20MB"
      max-request-size: "20MB"
  flyway:
    locations: "classpath:db/migration/postgresql"
    schemas: "public"

server:
  port: 8000
  compression:
    enabled: "true"
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 5120

alex:
  filesRootDir: "/var/lib/alex/data"
  version: "3.0.0"
  admin:
    email: "admin@alex.example"
    password: "admin"
    username: "admin"

selenium:
  grid:
    host: "selenium-hub"
    port: "4444"

ltsmin:
  path: ""

runtime: "kubernetes"
