name: Backend

on:
  push:
    branches:
      - developer
      - master
  pull_request:
    branches:
      - developer
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build with Maven
        run: mvn clean install -DskipTests package --file ./backend/pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build with Maven
        run: mvn verify --file ./backend/pom.xml