name: Docker

on:
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer

env:
  IMAGE_NAME_BACKEND: alex-backend
  IMAGE_NAME_FRONTEND: alex-frontend
  IMAGE_NAME_CLI: alex-cli

jobs:
  push-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          tags: ghcr.io/learnlib/alex/alex-backend:unstable

  push-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./frontend
          tags: ghcr.io/learnlib/alex/alex-frontend:unstable

  push-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./cli
          tags: ghcr.io/learnlib/alex/alex-cli:unstable
